### PR TITLE
animals index html

### PR DESCRIPTION
**Pull request by cathjeong**
@r-manet @manuelacassinello Please feel free to review!

### CODE REVIEW

**Comment by r-manet** [comment]
Will be doing so

**Comment by r-manet** [comment]
looks good, I think

**Comment by r-manet** [comment]
Have you checked with rails s what it looks like ?

**Comment by cathjeong** [comment]
Yessssss! If you have time, I can quickly show it to you. Lmk!

**Comment by cathjeong** [comment]
@r-manet

**Comment by cathjeong** [comment]
Sent you a slack message with a screenshot! @r-manet

**Pull request merged**
